spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgresql-17:5432/postgre-icp-erp}
    username: ${DB_USER:postgre-icp-erp}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  main:
    lazy-initialization: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    repair-on-validate: true
    baseline-version: "1"

server:
  tomcat:
    threads:
      max: 50
      min-spare: 5
  servlet:
    session:
      timeout: 8h
      cookie:
        http-only: true