spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/alfatahi_db}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:alfatahi}
    password: ${DB_PASS:changeme}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false