ALTER TABLE vidros DROP CONSTRAINT IF EXISTS vidros_tipo_check;
ALTER TABLE vidros ADD CONSTRAINT vidros_tipo_check
    CHECK (tipo IN ('COMUM', 'TEMPERADO', 'LAMINADO', 'ARAMADO', 'INSULADO', 'ESPELHO', 'ESPELHO_CEBRACE', 'ACRILICO'));
